IBM/event-notifications-python-admin-sdk

- README.md
signed-off-by: Nitish Kulkarni <nitish.kulkarni3@ibm.com>
> chore: add device count API, apispeclint errors fix and binary mode separation

- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
Includes the changes of cloud functions as a destination 
**Fixes:** #4861
no cloud functions destination suppport
we can configure the cloud functions as a destination in EN
> chore: add cloud functions destination support

- README.md
updated readme on private end points.
**Fixes:** [5450](https://github.ibm.com/Notification-Hub/planning/issues/5450)
More explanation on private end point was missing.
Given more details on private end point configuration
> chore: updated readme for private end point

- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
**Fixes:** https://github.ibm.com/notification-hub/planning/issues/5151
https://github.ibm.com/Notification-Hub/planning/issues/5638
opt in for email in not present.
added with optin for email as EN comply with regulatory standards
> chore: email optin changes

- examples/test_event_notifications_v1_examples.py
- test/integration/test_event_notifications_v1.py
PR includes example updates and test cases for push destinations.
Examples were not updated for push destinations
included examples and test cases for push destinations
> chore: update examples and test cases

- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/6034)
Pagerduty destination support is not there
added Pagerduty destination support
> chore: add Pagerduty destination

- .secrets.baseline
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
Signed-off-by: Nitish Kulkarni <nitish.kulkarni3@ibm.com>
PR includes changes of support for new destination service now.
**Fixes:** <! -- [link to issue](https://github.ibm.com/Notification-Hub/planning/issues/6640) -->
no support of service now destination
added support for service now destination
> chore: add service now destination support

- .secrets.baseline
Signed-off-by: Nitish Kulkarni <nitish.kulkarni3@ibm.com>
given fix for false positive audit.
handled false positive
> chore: audit fix for false positive

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- requirements.txt
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
Signed-off-by: Nitish Kulkarni <nitish.kulkarni3@ibm.com>
PR includes changes for support of FCM HTTP V1 support in EN.
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/6928)
Currently has only support for HTTP legacy API.
include support of FCM HTTP V1 support.
> chore: add FCM V1 destination support 

- .secrets.baseline
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
Includes support for code engine as a destination.
**Fixes:** (https://github.ibm.com/Notification-Hub/planning/issues/7627)
Please make sure that your PR fulfills the following requirements:
Code engine destination support was not there
added support for code engine as destination
> chore: add code engine destination support

- .secrets.baseline
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
Inlcludes changes for COS destination support
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/7746)
Please make sure that your PR fulfills the following requirements:
there was no support for adding COS as a destination
Added support for adding COS as new destination
> chore: adds COS destination support

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
Adds support for templates.
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/9860)
no support of templates
adds support for templates
> chore: adds templates support

- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
notification payload changes for custom email- bypass subscription
**Fixes:** <! -- [link to issue](https://github.ibm.com/Notification-Hub/planning/issues/10427) -->
bypass subscription for custom email is not present
notification payload changes for custom email- bypass subscription
> chore: custom email notification payload update

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
PR includes changes of test http destination connection
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/10123)
currently test API for http destination connection was not there
includes test API for http destination connection
> chore: add test http destination support

- .secrets.baseline
- .travis.yml
- Makefile
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/__init__.py
- ibm_eventnotifications/common.py
- ibm_eventnotifications/event_notifications_v1.py
- ibm_eventnotifications/version.py
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- setup.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_common.py
- test/unit/test_event_notifications_v1.py
Includes the vulnerability fix - urllib3 package
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/10746)
urllib3 is vulnerable
remediated vulnerabilities from urllib3 package
> chore: vulnerability fix

- ibm_eventnotifications/version.py
semantic deployment build is failing for version 
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/11008
version from version.py is not matching with the .bumpversion.cfg file specifies hence build is failing.
updated version.py to match version with .bumpversion.cfg
> chore: build issue fix

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
changes include api changes of
Collect failed events
Integration create api
Custom sms
enabled Countries get api
updatetemplate is replace to ReplaceTemplate (breaking change)
**Fixes:** 
https://github.ibm.com/Notification-Hub/planning/issues/10707
https://github.ibm.com/Notification-Hub/planning/issues/10954
https://github.ibm.com/Notification-Hub/planning/issues/11152
SDK was not having below mentioned API changes
Collect failed events
Integration create api
Custom sms
enabled Countries get api
updatetemplate is replace to ReplaceTemplate
Provided support for below mentioned API
Collect failed events
Integration create api
Custom sms
enabled Countries get api
updatetemplate is replace to ReplaceTemplate
> chore: adds custom sms support

- .secrets.baseline
- README.md
- event_notifications_v1.env.hide
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
PR includes changes for slack template, SMTP configuration and also vulnerability fixes 
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/13028
https://github.ibm.com/Notification-Hub/planning/issues/13037
https://github.ibm.com/Notification-Hub/planning/issues/13639
support for slack template and direct SMTP configuration for email does not exist
support for slack template and direct SMTP configuration for email
TemplateConfig is changed to TemplateConfigOneOfEmailTemplateConfig for email and TemplateConfigOneOfSlackTemplateConfig for slack.
> chore: smtp slack template and vulnerability fix

- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
SMTP configuration get and list response DKIM attributes txt_name and txt_value were not coming.
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/13951
SMTP configuration get and list response DKIM attributes txt_name and txt_value are not coming.
SMTP configuration get and list response has DKIM attributes with txt_name and txt_value.
> chore: code update

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- requirements.txt
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
https://github.ibm.com/Notification-Hub/planning/issues/14492
MMS support was not available, CF destination was supported from SDK
MMS has been enabled , CF destination support has been deprecated from SDK
> cf destination deprecation, mms support enabled

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- requirements.txt
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/14221
slack direct message was not supported
slack direct message is supported now.
Slack destination creation/update operation - DestinationConfigOneOfSlackDestinationConfig object is added with one more attribute "type" to define the destination type. Supported types are "incoming_webhook" and "direct_message
> chore: add slack direct message support

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/15830
support of webhook template was not there
support of webhook template was not there
> chore: webhook template support

- .secrets.baseline
- README.md
- ibm_eventnotifications/event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
https://github.ibm.com/Notification-Hub/planning/issues/16136
was having support for IBM cloud functions
Due to deprecation removing support of cloud functions
> chore: removed cloud functions support

- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
https://github.ibm.com/Notification-Hub/planning/issues/12339
cron scheduler support was not present
added cron scheduler support
> chore: cron scheduler support

- .releaserc
Migartion from Travis build tool to GitHub Actions
https://github.ibm.com/Notification-Hub/planning/issues/16783
travis ci build tool is not supported
migarting to new build tool Github Actions
> feat: workflow migration

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/16809
there is no support for pagerduty templates
support for pagerduty template
> chore: pagerduty template support

- README.md
Divya-Singh1693 <Divya.Singh1@ibm.com>
there is no support for pagerduty templates
support for pagerduty template
> chore: Pagerduty template release

- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/17206
there is no support for Event Streams destination
support for Event Streams destination and template
> chore: support for Event Streams and templates

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
support of markdown 
**Fixes:** 
https://github.ibm.com/Notification-Hub/planning/issues/17737
markdown support was not there for pretty formatting
adding support for markdown as part of notifications payload
> chore: adds markdown support from notification payload

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
support for predefined template and webhook put and patch
**Fixes:** 
https://github.ibm.com/Notification-Hub/planning/issues/17319
do not support for predefined templates
support for predefined templates
> chore: adds predefined templates support

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
Support for code engine templates (Application and Jobs)
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/18346
Please make sure that your PR fulfills the following requirements:
> feat: support for code engine templates

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/18288
Please make sure that your PR fulfills the following requirements:
> chore: adds test webhook destination suport

- .secrets.baseline
- README.md
- examples/test_event_notifications_v1_examples.py
- ibm_eventnotifications/event_notifications_v1.py
- test/integration/test_event_notifications_v1.py
- test/unit/test_event_notifications_v1.py
adds support of App Configuration as a destination
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/18531
no support app configuration as destination
adding support of app configuration as destination
> chore: adds support for app configuration as a destination
